apiVersion: apps/v1
kind: Deployment
metadata:
  name: hvac-deployment
  labels:
    app: hvac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hvac
  template:
    metadata:
      labels:
        app: hvac
    spec:
      imagePullSecrets:
        - name: docker-creds
      containers:
        - name: hvac-container
          image: log680h2022equipe20/lab2:latest
          env:
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: hvac-lab
                  key: hvac_host
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: hvac-secrets
                  key: hvac_token
                  optional: false